version: '3'

services:
  esphome:
    hostname: esphome
    container_name: "esphome_${DOMAIN_NAME}"
    image: esphome/esphome
    volumes:
      - "${DATA_PATH}:/config:rw"
      # Use local time for logging timestamps
      - /etc/localtime:/etc/localtime:ro
# для прошивки через COM порт сервера раскомментировать следующие две строки
#    devices:
#      - "/dev/ttyUSB0:/dev/ttyUSB0"
    network_mode: host
    restart: always
